### ISSUE TITLE
Typo in example in Data Format?

### ISSUE THREAD

**Issue by justhalf** [emorynlp/nlp4j-old#1]
When looking at [this file](https://github.com/emorynlp/nlp4j/blob/master/md/supplements/data-format.md), I noticed that the lemmatized column in the example doesn't match with the word ("founder" lemmatized into "owner" and "EmoryNLP" lemmatized into "emory").

Is this intentional?

Also, I noticed that "'s" in "He's" is lemmatized into "be" with the POS tag "VBZ". I can't reproduce this by using the EnglishMorphAnalyzer in nlp4j-morphology (following [this example](https://github.com/emorynlp/nlp4j-morphology/blob/master/src/test/java/edu/emory/mathcs/nlp/component/morph/english/EnglishMorphAnalyzerTest.java))

Is the example manually written? Or is there some other process that preprocess the words?

I'm asking this because I believe it's good if the example matches exactly the system behavior.

**Comment by jdchoi77** [comment]
The examples were hand-written so it had typos; I replaced them with automatically generated output so please take a look.

At the moment, we do not lemmatize "'s" into "be" because we thought it could be either "be" or "have"; however, our current lemmatizer can make use of the context (it didn't before) so we should be able to handle this part.  We'll include this feature for our next version.

https://github.com/emorynlp/nlp4j-morphology/issues/7

Thanks!

best,

Jinho
